service: desafio-ton

provider: 
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 128
  timeout: 3
  apiKeys:
    - mySecretAPIKey

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users_ton
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

functions:
  verifyToken:
    handler: src/auth/verifyToken.verifyToken

  hitCounter: 
    handler: src/counter/controllers/index.hitCounter
    description: Método para dar hit no Contador
    events: 
      - http:
          path: /counter/hit
          method: post
          cors: true
          authorizer: verifyToken

  getCounter: 
    handler: src/counter/controllers/index.getCounter
    description: Método para buscar valor do Contador
    events: 
      - http:
          path: /counter
          method: get
          cors: true

  createUser: 
    handler: src/users/controllers/index.createUser
    description: Método para criar novo usuário
    events: 
      - http:
          path: /user
          method: post
          cors: true

  getUser: 
    handler: src/users/controllers/index.getUser
    description: Método para buscar um usuário pelo id
    events: 
      - http:
          path: /user
          method: get
          cors: true